# Generated by Django 2.0 on 2019-08-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='product_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='product_cost',
            new_name='role',
        ),
    ]
